
export const ErrorResponseMessage = {
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
  BAD_REQUEST: 'BAD_REQUEST',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  MONGODB_CONNECTION_NOT_READY: 'MONGODB_CONNECTION_NOT_READY',
};
